<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Project>
    <PropertyGroup>
        <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
        <BaseOutputPath>$(MSBuildThisFileDirectory)bin\</BaseOutputPath>
    </PropertyGroup>
</Project>
